version: "3.5"

services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: "transferdb"
            MYSQL_USER: "transfer"
            MYSQL_PASSWORD: "123123123"
            MYSQL_ROOT_PASSWORD: "123123123"
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - developmentdb:/var/lib/MySQL
            - ./.docker/provision/mysql/init:/docker-entrypoint-initdb.d

volumes:
    developmentdb:
